//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIMS.Datalayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseFill
    {
        public int courseID { get; set; }
        public int subjectID { get; set; }
        public int subjectHoursPerWeek { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual Subject Subject { get; set; }
    }
}
