//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIMS.Datalayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lesson
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Lesson()
        {
            this.LessonDate = new HashSet<LessonDate>();
        }
    
        public long lessonID { get; set; }
        public int subjectID { get; set; }
        public int groupID { get; set; }
        public long teacherID { get; set; }
        public int roomID { get; set; }
        public int LessonOrder { get; set; }
        public byte DayOfWeek { get; set; }
    
        public virtual DayOfWeek DayOfWeek1 { get; set; }
        public virtual EIMSUser EIMSUser { get; set; }
        public virtual UniversityGroup UniversityGroup { get; set; }
        public virtual LessonOrder LessonOrder1 { get; set; }
        public virtual Room Room { get; set; }
        public virtual Subject Subject { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LessonDate> LessonDate { get; set; }
    }
}
