//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIMS.Datalayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class LessonPresence
    {
        public long lessonDateID { get; set; }
        public long studentID { get; set; }
        public bool presence { get; set; }
        public Nullable<byte> mark { get; set; }
    
        public virtual EIMSUser EIMSUser { get; set; }
        public virtual LessonDate LessonDate { get; set; }
    }
}
