//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIMS.Datalayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentGroup
    {
        public int studentGroupID { get; set; }
        public int groupID { get; set; }
        public long studentID { get; set; }
        public System.DateTime enrollmentDate { get; set; }
        public Nullable<System.DateTime> graduationDate { get; set; }
    
        public virtual EIMSUser EIMSUser { get; set; }
        public virtual UniversityGroup UniversityGroup { get; set; }
    }
}
