//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIMS.Datalayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentGroup
    {
        public int groupID { get; set; }
        public long studentID { get; set; }
        public System.DateTime enrollmentDate { get; set; }
        public Nullable<System.DateTime> graduationDate { get; set; }
    
        public virtual EIMSUser EIMSUser { get; set; }
        public virtual UniversityGroup UniversityGroup { get; set; }
    }
}
