//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIMS.Datalayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public long taskID { get; set; }
        public long lessonDateID { get; set; }
        public string homeTask { get; set; }
        public System.DateTime expiryDate { get; set; }
    
        public virtual LessonDate LessonDate { get; set; }
    }
}
