//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIMS.Datalayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public long taskID { get; set; }
        public long lessonDateID { get; set; }
        public string homeTask { get; set; }
        public System.DateTime expiryDate { get; set; }
    
        public virtual LessonDate LessonDate { get; set; }
    }
}
